config/routes.rb
Rails.application.routes.draw do
  get 'admin/login'
  get 'admin/logout'
  post 'admin/login'

  resources :employees

  resources :comapanies

  resources :companies

  resources :books

	get "home/index"
	get "home/second"

end

app/models/comapany.rb
class Comapany < ActiveRecord::Base
end

app/controllers/comapanies_controller.rb
class ComapaniesController < ApplicationController
  before_action :set_comapany, only: [:show, :edit, :update, :destroy]

  # GET /comapanies
  # GET /comapanies.json
  def index
    @comapanies = Comapany.all
  end

  # GET /comapanies/1
  # GET /comapanies/1.json
  def show
  end

  # GET /comapanies/new
  def new
    @comapany = Comapany.new
  end

  # GET /comapanies/1/edit
  def edit
  end

  # POST /comapanies
  # POST /comapanies.json
  def create
    @comapany = Comapany.new(comapany_params)

    respond_to do |format|
      if @comapany.save
        format.html { redirect_to @comapany, notice: 'Comapany was successfully created.' }
        format.json { render :show, status: :created, location: @comapany }
      else
        format.html { render :new }
        format.json { render json: @comapany.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comapanies/1
  # PATCH/PUT /comapanies/1.json
  def update
    respond_to do |format|
      if @comapany.update(comapany_params)
        format.html { redirect_to @comapany, notice: 'Comapany was successfully updated.' }
        format.json { render :show, status: :ok, location: @comapany }
      else
        format.html { render :edit }
        format.json { render json: @comapany.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comapanies/1
  # DELETE /comapanies/1.json
  def destroy
    @comapany.destroy
    respond_to do |format|
      format.html { redirect_to comapanies_url, notice: 'Comapany was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comapany
      @comapany = Comapany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comapany_params
      params.require(:comapany).permit(:name, :established, :intger)
    end
end

app/helpers/comapanies_helper.rb
module ComapaniesHelper
end

app/views/comapanies/_form.html.erb
<%= form_for(@comapany) do |f| %>
  <% if @comapany.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comapany.errors.count, "error") %> prohibited this comapany from being saved:</h2>

      <ul>
      <% @comapany.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :established %><br>
    <%= f.text_field :established %>
  </div>
  <div class="field">
    <%= f.label :intger %><br>
    <%= f.text_field :intger %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comapanies/edit.html.erb
<h1>Editing comapany</h1>

<%= render 'form' %>

<%= link_to 'Show', @comapany %> |
<%= link_to 'Back', comapanies_path %>

app/views/comapanies/index.html.erb
<h1>Listing comapanies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Established</th>
      <th>Intger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comapanies.each do |comapany| %>
      <tr>
        <td><%= comapany.name %></td>
        <td><%= comapany.established %></td>
        <td><%= comapany.intger %></td>
        <td><%= link_to 'Show', comapany %></td>
        <td><%= link_to 'Edit', edit_comapany_path(comapany) %></td>
        <td><%= link_to 'Destroy', comapany, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comapany', new_comapany_path %>

app/views/comapanies/new.html.erb
<h1>New comapany</h1>

<%= render 'form' %>

<%= link_to 'Back', comapanies_path %>

app/views/comapanies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comapany.name %>
</p>

<p>
  <strong>Established:</strong>
  <%= @comapany.established %>
</p>
<br/>
<br/>

 <%@company.employees.each do |emp|%>
 Name:<%=emp.name%><br/>
 Age:<%=emp.age%><br/>
 <%end%>
 


<%= link_to 'Edit', edit_comapany_path(@comapany) %> |
<%= link_to 'Back', comapanies_path %>